In [37]:
import numpy as np
import pandas as pd
import seaborn as sns

sns.set(rc={'figure.figsize': [10, 10]}, font_scale=1.3)

In [38]:
df = pd.read_csv('clean_data2.csv')
df

,Make,Model,Used since,Km,Transmission,City,Color,Fuel,Leather seats,Closing mirrors,...,Alloy wheels,Rear camera,GPS,Fog light,Rear spoiler,Cruise control,Power Seats,Central lock,Alarm,Price
0,Skoda,Rapid,2014.0,89000.0,automatic,Nasr city,Black,gas,False,False,...,False,False,False,True,False,False,True,True,True,225000.0
1,Skoda,Octavia A7,2015.0,120000.0,automatic,Cairo,Blue,gas,True,True,...,True,True,True,True,True,True,True,True,True,295000.0
2,Renault,Sandero,2016.0,70000.0,automatic,El Haram,Red,gas,False,False,...,False,False,False,False,False,False,False,False,False,200000.0
3,MG,ZS,2020.0,21000.0,automatic,El Haram,Red,gas,True,False,...,True,False,True,True,False,True,True,True,True,360000.0
4,MG,5,2021.0,28000.0,automatic,El Haram,Red,gas,True,True,...,True,False,False,True,False,False,True,False,True,340000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34949,Skoda,Octavia A5,2008.0,144000.0,automatic,Helwan,Black,gas,True,False,...,True,True,False,False,True,True,False,True,True,155000.0
34950,Toyota,Corolla,2019.0,59000.0,automatic,Mansoura,White,gas,True,True,...,True,False,False,False,False,True,False,True,True,362000.0
34951,Lada,2107,2011.0,43000.0,manual,Alexandria,Silver,gas,False,False,...,True,False,False,False,False,False,False,False,False,65000.0
34952,Renault,Logan,2013.0,0.0,manual,El Qanater El Khayreya,Red,gas,True,False,...,False,False,False,False,False,False,False,False,False,80000.0
34953,BMW,X1,2014.0,123000.0,automatic,Giza,Silver,gas,False,False,...,False,False,False,False,False,False,False,False,False,310000.0

In [39]:
df['Model'].value_counts()[:200]

Lanos       1345
Lancer      1270
Sunny       1177
Verna       1032
128          960
            ...
2008          26
C Elysee      26
X1            26
Creta         25
Solaris       25
Name: Model, Length: 200, dtype: int64

In [40]:
df['Model'].value_counts()[:200].index

Index(['Lanos', 'Lancer', 'Sunny', 'Verna', '128', 'Corolla', 'Optra',
       'Cerato', 'Logan', 'Nubira 2',
       ...
       'N200', 'Tivoli XLV', 'Grand Cerato', 'Sonata', 'Chery QQ || Chery qq',
       '2008', 'C Elysee', 'X1', 'Creta', 'Solaris'],
      dtype='object', length=200)

In [41]:
df = df[df['Model'].isin(df['Model'].value_counts()[:200].index)]
df

,Make,Model,Used since,Km,Transmission,City,Color,Fuel,Leather seats,Closing mirrors,...,Alloy wheels,Rear camera,GPS,Fog light,Rear spoiler,Cruise control,Power Seats,Central lock,Alarm,Price
1,Skoda,Octavia A7,2015.0,120000.0,automatic,Cairo,Blue,gas,True,True,...,True,True,True,True,True,True,True,True,True,295000.0
2,Renault,Sandero,2016.0,70000.0,automatic,El Haram,Red,gas,False,False,...,False,False,False,False,False,False,False,False,False,200000.0
3,MG,ZS,2020.0,21000.0,automatic,El Haram,Red,gas,True,False,...,True,False,True,True,False,True,True,True,True,360000.0
4,MG,5,2021.0,28000.0,automatic,El Haram,Red,gas,True,True,...,True,False,False,True,False,False,True,False,True,340000.0
5,Renault,Duster,2016.0,80000.0,manual,El Haram,White,gas,False,False,...,False,False,False,True,False,False,False,True,True,225000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34949,Skoda,Octavia A5,2008.0,144000.0,automatic,Helwan,Black,gas,True,False,...,True,True,False,False,True,True,False,True,True,155000.0
34950,Toyota,Corolla,2019.0,59000.0,automatic,Mansoura,White,gas,True,True,...,True,False,False,False,False,True,False,True,True,362000.0
34951,Lada,2107,2011.0,43000.0,manual,Alexandria,Silver,gas,False,False,...,True,False,False,False,False,False,False,False,False,65000.0
34952,Renault,Logan,2013.0,0.0,manual,El Qanater El Khayreya,Red,gas,True,False,...,False,False,False,False,False,False,False,False,False,80000.0
34953,BMW,X1,2014.0,123000.0,automatic,Giza,Silver,gas,False,False,...,False,False,False,False,False,False,False,False,False,310000.0

In [42]:
# df = df.copy().reset_index().drop('index', axis=1)
# df

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 31405 entries, 1 to 34953
Data columns (total 49 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Make                        31405 non-null  object
 1   Model                       31405 non-null  object
 2   Used since                  31405 non-null  float64
 3   Km                          31405 non-null  float64
 4   Transmission                31405 non-null  object
 5   City                        31405 non-null  object
 6   Color                       31405 non-null  object
 7   Fuel                        31405 non-null  object
 8   Leather seats               31405 non-null  bool
 9   Closing mirrors             31405 non-null  bool
 10  Intelligent parking system  31405 non-null  bool
 11  Sunroof                     31405 non-null  bool
 12  Fabric brushes              31405 non-null  bool
 13  Air Conditioning            31405 non-null  bool
 14  Power Steering              31405 non-null  bool
 15  Remote Keyless              31405 non-null  bool
 16  Electric mirrors            31405 non-null  bool
 17  Front Power Windows         31405 non-null  bool
 18  Back Power Windows          31405 non-null  bool
 19  Tinted Glass                31405 non-null  bool
 20  CD Player                   31405 non-null  bool
 21  DVD Player                  31405 non-null  bool
 22  Bluetooth                   31405 non-null  bool
 23  Multifunction               31405 non-null  bool
 24  Cassette Radio              31405 non-null  bool
 25  AUX                         31405 non-null  bool
 26  CD Changer                  31405 non-null  bool
 27  USB Port                    31405 non-null  bool
 28  Anti - theft System         31405 non-null  bool
 29  Side Airbag                 31405 non-null  bool
 30  ABS                         31405 non-null  bool
 31  EPS                         31405 non-null  bool
 32  EBD                         31405 non-null  bool
 33  ESP                         31405 non-null  bool
 34  Sensors                     31405 non-null  bool
 35  Rear sensors                31405 non-null  bool
 36  Driver Airbag               31405 non-null  bool
 37  Passenger Airbag            31405 non-null  bool
 38  Front sensors               31405 non-null  bool
 39  Alloy wheels                31405 non-null  bool
 40  Rear camera                 31405 non-null  bool
 41  GPS                         31405 non-null  bool
 42  Fog light                   31405 non-null  bool
 43  Rear spoiler                31405 non-null  bool
 44  Cruise control              31405 non-null  bool
 45  Power Seats                 31405 non-null  bool
 46  Central lock                31405 non-null  bool
 47  Alarm                       31405 non-null  bool
 48  Price                       31405 non-null  float64
dtypes: bool(40), float64(3), object(6)
memory usage: 3.6+ MB

In [44]:
df2 = df.copy()

In [9]:
df = pd.get_dummies(df, columns=['Make', 'Model', 'Transmission', 'City', 'Color', 'Fuel'], drop_first=True)
df

,Used since,Km,Leather seats,Closing mirrors,Intelligent parking system,Sunroof,Fabric brushes,Air Conditioning,Power Steering,Remote Keyless,...,Color_Petroleum,Color_Purple,Color_Red,Color_Silver,Color_White,Color_Yellow,Fuel_Hybrid,Fuel_diesel,Fuel_gas,Fuel_natural gas
1,2015.0,120000.0,True,True,True,True,True,True,True,True,...,0,0,0,0,0,0,0,0,1,0
2,2016.0,70000.0,False,False,False,False,False,False,False,False,...,0,0,1,0,0,0,0,0,1,0
3,2020.0,21000.0,True,False,True,False,True,True,True,True,...,0,0,1,0,0,0,0,0,1,0
4,2021.0,28000.0,True,True,False,True,False,True,False,True,...,0,0,1,0,0,0,0,0,1,0
5,2016.0,80000.0,False,False,True,False,True,True,True,True,...,0,0,0,0,1,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34949,2008.0,144000.0,True,False,False,False,False,True,True,True,...,0,0,0,0,0,0,0,0,1,0
34950,2019.0,59000.0,True,True,False,False,False,True,True,True,...,0,0,0,0,1,0,0,0,1,0
34951,2011.0,43000.0,False,False,False,False,False,False,False,False,...,0,0,0,1,0,0,0,0,1,0
34952,2013.0,0.0,True,False,False,False,False,True,False,False,...,0,0,1,0,0,0,0,0,1,0
34953,2014.0,123000.0,False,False,False,False,False,False,False,False,...,0,0,0,1,0,0,0,0,1,0

In [10]:
x = df.drop('Price', axis=1)
y = df['Price']

In [11]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.15)

In [12]:
x_test.shape

(4711, 411)

In [13]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

scaler.fit(x_train)
x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)

In [14]:
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [15]:
models = {
#     "LR": LinearRegression(),
#     "KNNR" : KNeighborsRegressor(), 
#     "SVR": SVR(),
#     "DT": DecisionTreeRegressor(),
#     "RF": RandomForestRegressor(),
    "XGBR": XGBRegressor(n_estimators=300, max_depth=5)
}

In [ ]:
# from sklearn.decomposition import PCA

# pca = PCA(0.9)

# pca.fit(x_train)
# x_train = pca.transform(x_train)
# x_test = pca.transform(x_test)

In [ ]:
x_train.shape

In [16]:
for name, model in models.items():
    print(f'Using model: {name}')
    model.fit(x_train, y_train)
    y_pred = model.predict(x_test)
    print(f'R2 Score: {r2_score(y_test, y_pred)}')  
    print(f'RMSE Score: {np.sqrt(mean_squared_error(y_test, y_pred))}')  
    print('-'*30)

Using model: XGBR
R2 Score: 0.9276885205677537
RMSE Score: 23941.77213185463
------------------------------

In [17]:
df['Price'].describe()

count     31405.000000
mean     131000.302531
std       89145.105289
min       10000.000000
25%       65000.000000
50%      110000.000000
75%      178000.000000
max      423000.000000
Name: Price, dtype: float64

In [ ]:
from sklearn.model_selection import RandomizedSearchCV, GridSearchCV


model = XGBRegressor()
params = [
    {'max_depth': range(1, 20), 'n_estimators': range(100, 501, 50)}
]

In [ ]:
# gs = GridSearchCV(estimator=model, param_grid=params, cv=10, scoring='r2', n_jobs=-1, verbose=3)
rs = RandomizedSearchCV(estimator=model, param_distributions=params, cv=10, scoring='r2', n_jobs=-1, verbose=3)

In [ ]:
rs.fit(x_train, y_train)

In [ ]:
rs.best_score_

In [ ]:
rs.best_params_

In [ ]:
model = rs.best_estimator_

In [18]:
model.predict(x_test)

array([ 79964.266, 148711.69 ,  58866.863, ..., 339235.22 , 102706.08 ,
       156839.02 ], dtype=float32)

In [19]:
y_test

409       70000.0
22255    138000.0
3849      50000.0
6198      22000.0
34908    150000.0
           ...
10783    260000.0
19675     70000.0
27665    355000.0
34867    110000.0
8992     140000.0
Name: Price, Length: 4711, dtype: float64

In [20]:
x

,Used since,Km,Leather seats,Closing mirrors,Intelligent parking system,Sunroof,Fabric brushes,Air Conditioning,Power Steering,Remote Keyless,...,Color_Petroleum,Color_Purple,Color_Red,Color_Silver,Color_White,Color_Yellow,Fuel_Hybrid,Fuel_diesel,Fuel_gas,Fuel_natural gas
1,2015.0,120000.0,True,True,True,True,True,True,True,True,...,0,0,0,0,0,0,0,0,1,0
2,2016.0,70000.0,False,False,False,False,False,False,False,False,...,0,0,1,0,0,0,0,0,1,0
3,2020.0,21000.0,True,False,True,False,True,True,True,True,...,0,0,1,0,0,0,0,0,1,0
4,2021.0,28000.0,True,True,False,True,False,True,False,True,...,0,0,1,0,0,0,0,0,1,0
5,2016.0,80000.0,False,False,True,False,True,True,True,True,...,0,0,0,0,1,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34949,2008.0,144000.0,True,False,False,False,False,True,True,True,...,0,0,0,0,0,0,0,0,1,0
34950,2019.0,59000.0,True,True,False,False,False,True,True,True,...,0,0,0,0,1,0,0,0,1,0
34951,2011.0,43000.0,False,False,False,False,False,False,False,False,...,0,0,0,1,0,0,0,0,1,0
34952,2013.0,0.0,True,False,False,False,False,True,False,False,...,0,0,1,0,0,0,0,0,1,0
34953,2014.0,123000.0,False,False,False,False,False,False,False,False,...,0,0,0,1,0,0,0,0,1,0

In [21]:
for f in x.columns:
    print(f)

Used since
Km
Leather seats
Closing mirrors
Intelligent parking system
Sunroof
Fabric brushes
Air Conditioning
Power Steering
Remote Keyless
Electric mirrors
Front Power Windows
Back Power Windows
Tinted Glass
CD Player
DVD Player
Bluetooth
Multifunction
Cassette Radio
AUX
CD Changer
USB Port
Anti - theft System
Side Airbag
ABS
EPS
EBD
ESP
Sensors
Rear sensors
Driver Airbag
Passenger Airbag
Front sensors
Alloy wheels
Rear camera
GPS
Fog light
Rear spoiler
Cruise control
Power Seats
Central lock
Alarm
Make_BMW
Make_Baic
Make_Brilliance
Make_Byd
Make_Changan
Make_Chery
Make_Chevrolet
Make_Citroën
Make_Daewoo
Make_Daihatsu
Make_Fiat
Make_Ford
Make_Geely
Make_Honda
Make_Hyundai
Make_Isuzu
Make_Jac
Make_Jeep
Make_Kia
Make_Lada
Make_Lifan
Make_MG
Make_Mazda
Make_Mercedes
Make_Mitsubishi
Make_Nissan
Make_Opel
Make_Peugeot
Make_Proton
Make_Renault
Make_Saipa
Make_Seat
Make_Senova
Make_Skoda
Make_Speranza
Make_Ssang Yong
Make_Subaru
Make_Suzuki
Make_Toyota
Make_Volkswagen
Model_125
Model_127
Model_128
Model_131
Model_132
Model_1500
Model_190
Model_200
Model_2008
Model_206
Model_2105
Model_2107
Model_2110
Model_230
Model_3 || Mazda 3
Model_3008
Model_301
Model_307
Model_316
Model_318
Model_320
Model_323
Model_405
Model_406
Model_5
Model_504
Model_505
Model_508
Model_523
Model_525
Model_6
Model_A1
Model_A11
Model_A113
Model_A516
Model_A620 || A620
Model_Accent
Model_Accent RB
Model_Accord
Model_Alto
Model_Arrizo 5
Model_Astra
Model_Atos
Model_Avante
Model_Avanza
Model_Aveo
Model_Ax
Model_B 150
Model_Beetle
Model_Benni
Model_Bora
Model_C 180
Model_C 200
Model_C Elysee
Model_C3
Model_C4
Model_Captiva
Model_Captur
Model_Carens
Model_Cerato
Model_Charade
Model_Cherokee
Model_Chery QQ || Chery qq
Model_City
Model_Civic
Model_Clio
Model_Corolla
Model_Corsa
Model_Creta
Model_Cruze
Model_D max
Model_Dogan
Model_Duster
Model_E 200
Model_E 240
Model_Elantra
Model_Elantra AD
Model_Elantra CN7
Model_Elantra HD
Model_Elantra MD
Model_Emgrand 7
Model_Emgrand X7
Model_Envy
Model_Escort
Model_Excel
Model_F3
Model_FRV
Model_FSV
Model_Fabia
Model_Fantasia
Model_Favorit
Model_Felicia
Model_Felicia combi
Model_Fiesta
Model_Fluence
Model_Focus
Model_Galena
Model_Gen 2
Model_Getz
Model_Golf
Model_Gran max
Model_Grand Cerato
Model_Grand Cherokee
Model_Granta
Model_H1
Model_Hilux
Model_I10
Model_IX 35
Model_Ibiza
Model_Impreza
Model_Insignia
Model_Jetta
Model_Juke
Model_Juliet
Model_Kadjar
Model_L3
Model_Lacetti
Model_Lancer
Model_Lanos
Model_Lanos 2
Model_Leganza
Model_Leon
Model_Liberty
Model_Logan
Model_M11
Model_Maruti
Model_Matiz
Model_Matrix
Model_Megane
Model_Mondeo
Model_N200
Model_N300
Model_Niva
Model_Nubira 1
Model_Nubira 2
Model_Octavia A4
Model_Octavia A5
Model_Octavia A7
Model_Optra
Model_Pajero
Model_Palio
Model_Pandino
Model_Passat
Model_Persona
Model_Picanto
Model_Pick up
Model_Pickup
Model_Pointer
Model_Polo
Model_Polonez
Model_Pride
Model_Punto
Model_Qashqai
Model_Rainbow
Model_Regata
Model_Renegade
Model_Rio
Model_Ritmo
Model_Rx5
Model_S2
Model_Sandero
Model_Sandero Step Way
Model_Sentra
Model_Sephia
Model_Shahin
Model_Shuma
Model_Siena
Model_Solaris
Model_Sonata
Model_Soul
Model_Spark
Model_Spectra
Model_Sportage
Model_Sunny
Model_Swift
Model_T-Series
Model_Tempra
Model_Terios
Model_Tiggo
Model_Tiida
Model_Tipo
Model_Tivoli XLV
Model_Toledo
Model_Tucson
Model_Uno
Model_V5
Model_Van
Model_Vectra
Model_Verna
Model_Vitara
Model_Waja
Model_Wira
Model_Wrangler
Model_X1
Model_X3
Model_XTrail || XTrail
Model_XV
Model_Yaris
Model_ZS
Transmission_DSG
Transmission_automatic
Transmission_manual
City_6 October
City_Abu Hummus
City_Abu Kabir
City_Abu Qir
City_Agamy
City_Ain Shams
City_Al Shorouk
City_Alexandria
City_Amreya
City_Ashmoun
City_Aswan
City_Asyut
City_Banha
City_Beheira
City_Beni Suef
City_Bilbeis
City_Borg el arab
City_Cairo
City_Dakahlia
City_Damanhur
City_Damietta
City_Dikirnis
City_Dokki
City_Dyarb Negm
City_Edku
City_El Bagour
City_El Gamaleya
City_El Gouna
City_El Haram
City_El Katameya
City_El Mahalla
City_El Manial
City_El Marg
City_El Minya
City_El Qanater El Khayreya
City_El Salam City
City_El Senbellawein
City_El Wadi El Gedid
City_El-Alamein
City_El-Arish
City_Faiyum
City_Faqous
City_Gharbia
City_Giza
City_Heliopolis
City_Helwan
City_Hurghada
City_Imbaba
City_Ismailia
City_Kafr El Zayat
City_Kafr Shukr
City_Kafr el-Dawwar
City_Kafr el-Sheikh
City_Kerdasa
City_Khanka
City_Kom Hamada
City_Kom Ombo
City_Luxor
City_Maadi
City_Madinaty
City_Mansoura
City_Marsa Alam
City_Marsa Matrouh
City_Menouf
City_Minya Al Qamh
City_Mit Ghamr
City_Mohandessin
City_Mokattam
City_Monufia
City_Nasr city
City_New Administrative Capital
City_Obour City
City_Port Said
City_Qalyub
City_Qalyubia
City_Qena
City_Quesna
City_Ras Gharib
City_Red Sea
City_Rosetta
City_Sadat City
City_Safaga
City_Saft El Laban
City_Sharm el-Sheikh
City_Sharqia
City_Sheikh Zayed City
City_Sheraton
City_Shibin El Qanater
City_Shibin el Kom
City_Shobra
City_Sohag
City_Suez
City_Tagamo3 - New Cairo
City_Tala
City_Tanta
City_Touhk
City_Warraq
City_Zagazig
City_Zamalek
City_Zefta
Color_Black
Color_Blue
Color_Bronze
Color_Brown
Color_Champagne
Color_Cyan
Color_Dark blue
Color_Dark green
Color_Dark red
Color_Eggplant
Color_Gold
Color_Gray
Color_Green
Color_Light grey
Color_Mocha
Color_Olive
Color_Orange
Color_Petroleum
Color_Purple
Color_Red
Color_Silver
Color_White
Color_Yellow
Fuel_Hybrid
Fuel_diesel
Fuel_gas
Fuel_natural gas

In [22]:
def ret_dummies(feat, value):
    make_values = sorted(df2[feat].unique())[1:]
    dummies = []
    for val in make_values:
        if val == value:
            dummies.append(1)
        else:
            dummies.append(0)
    return dummies

In [23]:
ret_dummies('Color', 'Bronze')

[0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [43]:
df2

,Make,Model,Used since,Km,Transmission,City,Color,Fuel,Leather seats,Closing mirrors,...,Alloy wheels,Rear camera,GPS,Fog light,Rear spoiler,Cruise control,Power Seats,Central lock,Alarm,Price
1,Skoda,Octavia A7,2015.0,120000.0,automatic,Cairo,Blue,gas,True,True,...,True,True,True,True,True,True,True,True,True,295000.0
2,Renault,Sandero,2016.0,70000.0,automatic,El Haram,Red,gas,False,False,...,False,False,False,False,False,False,False,False,False,200000.0
3,MG,ZS,2020.0,21000.0,automatic,El Haram,Red,gas,True,False,...,True,False,True,True,False,True,True,True,True,360000.0
4,MG,5,2021.0,28000.0,automatic,El Haram,Red,gas,True,True,...,True,False,False,True,False,False,True,False,True,340000.0
5,Renault,Duster,2016.0,80000.0,manual,El Haram,White,gas,False,False,...,False,False,False,True,False,False,False,True,True,225000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34949,Skoda,Octavia A5,2008.0,144000.0,automatic,Helwan,Black,gas,True,False,...,True,True,False,False,True,True,False,True,True,155000.0
34950,Toyota,Corolla,2019.0,59000.0,automatic,Mansoura,White,gas,True,True,...,True,False,False,False,False,True,False,True,True,362000.0
34951,Lada,2107,2011.0,43000.0,manual,Alexandria,Silver,gas,False,False,...,True,False,False,False,False,False,False,False,False,65000.0
34952,Renault,Logan,2013.0,0.0,manual,El Qanater El Khayreya,Red,gas,True,False,...,False,False,False,False,False,False,False,False,False,80000.0
34953,BMW,X1,2014.0,123000.0,automatic,Giza,Silver,gas,False,False,...,False,False,False,False,False,False,False,False,False,310000.0

In [48]:
len(x.columns)

412

In [24]:
import random

In [25]:
car = []
main_ft = [2019, 20000]
eq_ft = [random.choice([1, 0]) for i in range(40)]
make = ret_dummies('Make', 'Nissan')
car_model = ret_dummies('Model', 'Corolla')
transmission = ret_dummies('Transmission', 'manual')
city = ret_dummies('City', 'Banha')
color = ret_dummies('Color', 'Purple')
fuel = ret_dummies('Fuel', 'gas')

car += main_ft + eq_ft + make + car_model + transmission + city + color + fuel
car = [car]
car

[[2019,
  20000,
  1,
  1,
  1,
  1,
  1,
  1,
  0,
  0,
  1,
  1,
  1,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  1,
  1,
  1,
  0,
  1,
  0,
  1,
  0,
  1,
  1,
  0,
  0,
  0,
  0,
  1,
  0,
  1,
  0,
  1,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0]]

In [28]:
len(car[0])

411

In [29]:
car = scaler.transform(car)
car

array([[ 1.19180479e+00, -1.04059068e+00,  8.69123589e-01,
         3.54554935e+00,  5.50069189e+00,  3.49217047e+00,
         2.66668566e+00,  7.79479362e-01, -1.02665312e+00,
        -6.17568633e-01,  1.90366463e+00,  7.97346848e-01,
         9.79090217e-01, -3.60622046e-01, -3.85324292e-01,
         3.49403960e+00, -4.83563920e-01, -2.53178786e-01,
        -1.15675940e+00, -5.81762540e-01,  3.51573042e+00,
         1.72799417e+00,  3.63719825e+00, -2.65842488e-01,
         1.48828174e+00, -2.62597091e-01,  1.86537146e+00,
        -8.51160164e-02,  3.21033116e+00,  3.27229197e+00,
        -6.19710468e-01, -4.32717301e-01, -1.72918608e-01,
        -6.14675485e-01,  3.36259631e+00, -1.91993559e-01,
         2.22975606e+00, -2.32859973e-01,  3.50248421e+00,
        -2.32143915e-01,  1.09674006e+00, -5.07785025e-01,
        -1.29756743e-01, -1.49940036e-02, -7.12953204e-02,
        -1.40535271e-01, -3.29782955e-02, -1.10672052e-01,
        -3.16390627e-01, -5.84864672e-02, -2.44778710e-01,
        -7.61745507e-02, -3.49449944e-01, -8.48924691e-02,
        -1.33439416e-01, -9.30211688e-02, -3.71414424e-01,
        -6.54899920e-02, -3.24041085e-02, -1.21764701e-01,
        -2.52759668e-01, -1.61311647e-01, -2.03038789e-02,
        -9.24046139e-02, -9.07406865e-02, -1.44232657e-01,
        -2.09466261e-01,  4.21257481e+00, -1.86363555e-01,
        -1.82344366e-01, -7.15602371e-02, -2.28899612e-01,
        -2.93659644e-02, -9.28160900e-02, -2.87199414e-02,
        -1.80582272e-01, -1.83547245e-01, -2.80590986e-02,
        -4.54383326e-02, -1.94185419e-01, -1.76899585e-01,
        -1.52796436e-01, -3.51818565e-02, -9.87897716e-02,
        -1.78134560e-01, -8.71028688e-02, -7.07625720e-02,
        -3.67483182e-02, -3.06172823e-02, -8.68842851e-02,
        -2.80590986e-02, -3.51818565e-02, -7.56754429e-02,
        -1.04251285e-01, -2.93659644e-02, -3.29782955e-02,
        -6.16278505e-02, -3.35426968e-02, -5.58481059e-02,
        -5.88080487e-02, -7.07625720e-02, -6.13208502e-02,
        -5.71823068e-02, -6.49105344e-02, -8.44436502e-02,
        -4.97854794e-02, -6.34391304e-02, -9.17840585e-02,
        -5.20050967e-02, -4.33196850e-02, -3.96971879e-02,
        -4.10928061e-02, -4.10928061e-02, -3.35426968e-02,
        -4.28834955e-02, -8.90467058e-02, -1.13921649e-01,
        -4.24428567e-02, -1.27499564e-01, -6.00773995e-02,
        -3.12242094e-02, -4.70651726e-02, -6.54899920e-02,
        -1.14426728e-01, -4.28834955e-02, -5.84864672e-02,
        -3.18196063e-02, -1.30054933e-01, -2.80590986e-02,
        -2.44896939e-02, -4.10928061e-02, -3.29782955e-02,
        -2.73823631e-02, -6.43259455e-02, -3.51818565e-02,
        -2.73823631e-02, -3.06172823e-02, -3.06172823e-02,
        -4.01677470e-02, -3.35426968e-02, -8.02946728e-02,
        -1.45982141e-01, -4.01677470e-02, -8.05306284e-02,
        -2.93659644e-02, -2.87199414e-02, -8.26246916e-02,
        -6.77591257e-02,  6.32990460e+00, -7.95827163e-02,
        -2.99981252e-02, -8.10005307e-02, -6.54899920e-02,
        -4.46028565e-02, -5.97625538e-02, -6.13208502e-02,
        -3.24041085e-02, -8.64455094e-02, -6.37360841e-02,
        -3.51818565e-02, -8.66651666e-02, -9.32258119e-02,
        -1.23652020e-01, -3.06172823e-02, -6.19333519e-02,
        -4.01677470e-02, -1.13414436e-01, -1.32564270e-01,
        -2.99981252e-02, -3.77567243e-02, -3.57116064e-02,
        -6.31408025e-02, -4.15476635e-02, -9.07406865e-02,
        -3.24041085e-02, -3.92210195e-02, -5.55096091e-02,
        -5.51690610e-02, -4.10928061e-02, -4.24428567e-02,
        -4.78580361e-02, -7.93440139e-02, -3.40977985e-02,
        -2.87199414e-02, -4.41792420e-02, -7.41584294e-02,
        -4.24428567e-02, -4.15476635e-02, -5.41347216e-02,
        -5.12757909e-02, -8.02946728e-02, -3.57116064e-02,
        -4.33196850e-02, -5.78380140e-02, -3.67483182e-02,
        -5.41347216e-02, -3.92210195e-02, -4.58504082e-02,
        -3.51818565e-02, -2.05933539e-01, -2.11020521e-01,
        -8.57832633e-02, -3.77567243e-02, -3.24041085e-02,
        -5.41347216e-02, -1.38582360e-01, -3.72559143e-02,
        -9.58477868e-02, -4.24428567e-02, -9.62450525e-02,
        -9.95601708e-02, -3.12242094e-02, -2.99981252e-02,
        -7.07625720e-02, -3.35426968e-02, -7.18241966e-02,
        -1.36033429e-01, -9.93681091e-02, -6.07022621e-02,
        -4.41792420e-02, -1.53820341e-01, -3.06172823e-02,
        -2.87199414e-02, -3.87390351e-02, -7.15602371e-02,
        -2.93659644e-02, -7.54246789e-02, -4.06328918e-02,
        -8.84033631e-02, -3.29782955e-02, -6.80375405e-02,
        -4.62588437e-02, -7.44133647e-02, -6.88661559e-02,
        -7.15602371e-02, -2.93659644e-02, -6.60644534e-02,
        -3.18196063e-02, -8.53389949e-02, -3.57116064e-02,
        -3.18196063e-02, -3.24041085e-02, -6.03906273e-02,
        -4.90235101e-02, -7.46674488e-02, -6.28410810e-02,
        -1.30352487e-01, -5.44816573e-02, -8.07659124e-02,
        -2.80590986e-02, -2.87199414e-02, -4.70651726e-02,
        -5.37855743e-02, -4.82496263e-02, -5.48264236e-02,
        -1.95738170e-01, -6.60644534e-02, -6.96851028e-02,
        -6.19333519e-02, -5.41347216e-02, -1.00705150e-01,
        -4.37515583e-02, -8.28541848e-02, -2.80590986e-02,
        -3.18196063e-02, -3.18196063e-02, -6.77591257e-02,
        -3.24041085e-02, -1.33729947e-01, -1.12393495e-01,
        -1.83547245e-01, -3.82510147e-02, -3.18196063e-02,
        -3.77567243e-02, -4.78580361e-02, -2.80590986e-02,
        -3.29782955e-02, -2.99981252e-02, -2.80590986e-02,
        -5.71823068e-02, -4.62588437e-02, -2.44896939e-02,
        -8.73981123e-01,  8.80600515e-01, -1.71419206e-01,
        -2.03038789e-02, -3.40977985e-02, -3.77567243e-02,
        -6.43259455e-02, -7.20872093e-02, -7.78968255e-02,
        -3.39171924e-01, -2.73823631e-02, -3.87390351e-02,
        -6.00773995e-02, -1.21923027e-01,  1.30428289e+01,
        -1.12222481e-01, -1.00324885e-01, -4.06328918e-02,
        -3.35426968e-02, -4.99074995e-01, -1.48636771e-01,
        -5.97625538e-02, -1.18231029e-01, -3.51818565e-02,
        -5.65190933e-02, -3.77567243e-02, -1.61956783e-02,
        -3.35426968e-02, -1.83648612e-02, -6.12070301e-03,
        -1.72803678e-01, -1.83648612e-02, -7.83821176e-02,
        -3.62336508e-02, -6.07022621e-02, -1.21447465e-01,
        -3.87390351e-02, -5.65190933e-02, -3.51818565e-02,
        -2.59762167e-02, -8.65614335e-03, -2.52438718e-02,
        -1.12905062e-01, -4.78580361e-02, -1.54838096e-01,
        -2.98358214e-01, -1.24430456e-01, -1.09626849e-01,
        -5.84864672e-02, -6.74795832e-02, -1.52153319e-01,
        -3.06172823e-02, -1.61956783e-02, -4.46028565e-02,
        -1.18880884e-01, -2.20734707e-02, -4.06328918e-02,
        -2.66885259e-02, -1.06017658e-02, -5.65190933e-02,
        -1.04983212e-01, -3.96971879e-02, -1.15763387e-01,
        -6.12070301e-03, -4.41792420e-02, -3.12242094e-02,
        -4.15476635e-02, -5.68516547e-02, -9.60466175e-02,
        -7.39026340e-02, -1.30054933e-01, -1.50859606e-01,
        -8.65614335e-03, -9.58477868e-02, -9.58477868e-02,
        -3.77567243e-02, -1.54075351e-01, -8.23945766e-02,
        -4.24428567e-02, -1.22420940e-02, -7.54246789e-02,
        -2.03038789e-02, -5.30804705e-02, -1.22420940e-02,
        -3.77567243e-02, -3.92210195e-02, -1.59097705e-01,
        -7.44133647e-02, -3.96971879e-02, -4.37515583e-02,
        -6.88661559e-02, -1.14929701e-01, -9.95601708e-02,
        -1.29756743e-01, -1.39142918e-01, -3.18196063e-02,
        -1.17741415e-01, -3.35426968e-02, -6.91401954e-02,
        -9.93681091e-02, -2.20734707e-02, -3.77567243e-02,
        -4.23343668e-01, -2.34375823e-01, -8.94731114e-02,
        -9.89829116e-02, -9.34300221e-02, -1.57231323e-01,
        -1.97382948e-01, -1.07329003e-01, -2.67856115e-01,
        -7.39026340e-02, -1.90836838e-01, -2.83742873e-01,
        -1.65898250e-01, -2.23316393e-01, -1.04067533e-01,
        -9.72313756e-02, -5.97625538e-02, -1.04251285e-01,
         1.77984751e+01, -3.17249653e-01, -4.45221812e-01,
        -3.90564859e-01, -7.56754429e-02, -4.78580361e-02,
        -8.33113262e-02,  1.32124674e-01, -8.92601551e-02]])

In [50]:
car.shape

(1, 412)

In [30]:
prediction = model.predict(car)[0]
prediction

279458.0

In [31]:
import joblib

In [33]:
# joblib.dump(pca, 'pca.h5')
joblib.dump(scaler, 'scaler.h5')
joblib.dump(model, 'model.h5')

['model.h5']

In [45]:
df2.to_csv('data.csv', index=False)

In [48]:
int(prediction)

279458